backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "site"
    label: "Site Settings"
    files:
      - file: "admin/site-settings.yml"
        label: "Business Info"
        name: "business_info"
        fields:
          - { label: "Business Name", name: "business_name", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
