backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "Pages"
    files:

      - label: "Homepage"
        name: "home"
        file: "index.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}

      - label: "Services"
        name: "services"
        file: "services.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}

      - label: "About"
        name: "about"
        file: "about.html"
        fields:
          - {label: "Content", name: "content", widget: "text"}

      - label: "Contact"
        name: "contact"
        file: "contact.html"
        fields:
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
